import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";

import { TRPCReactProvider } from "~/trpc/react";
import { NavBar } from "../components/navbar";
import { Sidebar } from "../components/sidebar";
import { cn } from "~/components/_utils/cn";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <TRPCReactProvider>
      <html lang="en" className={`${GeistSans.variable}`}>
        <body
          className={cn(
            "bg-background font-sans antialiased",
            GeistSans.variable,
          )}
        >
          <main className="flex h-screen flex-col items-center justify-center bg-black text-white">
            <NavBar />
            <div className="flex w-full flex-1 flex-row">
              <Sidebar />
              {children}
            </div>
          </main>
        </body>
      </html>
    </TRPCReactProvider>
  );
}
